# Generated by Django 3.0.3 on 2020-02-07 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=1024)),
                ('mortality', models.FloatField()),
                ('morbidity', models.FloatField()),
                ('info_diagnostic', models.TextField()),
                ('info_managerial', models.TextField()),
            ],
        ),
    ]
