# Generated by Django 3.0.7 on 2020-07-08 16:34

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pincode',
            fields=[
                ('pincode', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinLengthValidator(6)])),
                ('area', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('state_code', models.IntegerField()),
                ('province', models.CharField(max_length=30)),
                ('province2', models.CharField(max_length=30)),
                ('accuracy', models.IntegerField()),
                ('located_at', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.RemoveField(
            model_name='person',
            name='id',
        ),
        migrations.AddField(
            model_name='disease',
            name='info_spread',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disease',
            name='info_url',
            field=models.URLField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disease',
            name='vacination_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='disease',
            name='zoonotic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hospital',
            name='name',
            field=models.CharField(default=None, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='aadhar_number',
            field=models.CharField(default=0, max_length=12, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinLengthValidator(12)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='animal_owner',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='pincode',
            field=models.CharField(default=None, max_length=6, validators=[django.core.validators.MinLengthValidator(6)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='death',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='full_name',
            field=models.CharField(max_length=24),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='report',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disdata.Hospital'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='pincode',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='disdata.Pincode'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='pincode',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='disdata.Pincode'),
            preserve_default=False,
        ),
    ]
