# Generated by Django 3.0.7 on 2020-07-08 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disdata', '0002_auto_20200708_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pincode',
            name='area',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='pincode',
            name='province',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='pincode',
            name='province2',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='pincode',
            name='state',
            field=models.CharField(max_length=40),
        ),
    ]
