# Generated by Django 3.0.3 on 2020-02-07 08:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('disdata', '0002_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='morbidity',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='mortality',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='reported_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
