# Generated by Django 3.0.3 on 2020-02-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disdata', '0003_auto_20200207_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='morbidity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='mortality',
            field=models.FloatField(),
        ),
    ]
