# Generated by Django 3.0.7 on 2020-07-13 10:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disdata', '0005_auto_20200708_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='category',
            field=models.CharField(choices=[('Water', 'Water borne'), ('Food', 'Food borne'), ('Vector', 'Vector borne'), ('Air', 'Air borne')], default='None', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disease',
            name='info_precautions',
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disease',
            name='suseptible_prone_age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pincode',
            name='age_frequency_vector',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=[1, 1, 1], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pincode',
            name='altitude',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pincode',
            name='humidity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pincode',
            name='population',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pincode',
            name='rainfall',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pincode',
            name='sanitation_condition',
            field=models.CharField(default="", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pincode',
            name='temprature',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='verified',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
