# Generated by Django 3.0.7 on 2020-07-15 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disdata', '0006_auto_20200713_1045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name_plural': 'Census'},
        ),
    ]
