# Generated by Django 3.0.7 on 2020-07-15 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disdata', '0007_auto_20200715_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='pincode',
            name='is_alerted',
            field=models.BooleanField(default=False),
        ),
    ]
