# Generated by Django 3.0.7 on 2020-07-18 16:05

import disdata.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disdata', '0012_auto_20200718_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='animal_infection',
        ),
        migrations.RemoveField(
            model_name='report',
            name='human_infection',
        ),
        migrations.AddField(
            model_name='report',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[disdata.models.validate_report_category]),
        ),
    ]
