# Generated by Django 3.0.7 on 2020-07-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disdata', '0013_auto_20200718_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='category',
            field=models.CharField(blank=True, choices=[('human', 'Human'), ('animal', 'Animal')], max_length=255, null=True),
        ),
    ]
