# Generated by Django 3.0.7 on 2020-07-21 19:12

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('disdata', '0014_auto_20200718_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='infections',
        ),
        migrations.RemoveField(
            model_name='report',
            name='morbidity',
        ),
        migrations.RemoveField(
            model_name='report',
            name='mortality',
        ),
        migrations.AddField(
            model_name='disease',
            name='threshold_alert',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='disease',
            name='victim_id',
            field=models.CharField(choices=[('pt', 'Poultry'), ('gt', 'Goat'), ('pg', 'Pig'), ('bf', 'Buffalo'), ('sp', 'Ship')], default='pt', max_length=2),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Outbreak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infected', models.IntegerField(default=0)),
                ('death', models.IntegerField(default=0)),
                ('outbreak_over', models.BooleanField(default=False)),
                ('first_alert', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('human', 'Human'), ('animal', 'Animal')], max_length=10)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disdata.Disease')),
                ('start_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disdata.Report')),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attn', models.CharField(choices=[('danger', 'danger'), ('yellow', 'yellow')], max_length=6)),
                ('msg_notice', models.BooleanField(default=True)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('msg_head', models.CharField(max_length=20)),
                ('msg_body', models.CharField(max_length=255)),
                ('approved', models.BooleanField(default=False)),
                ('action', models.CharField(max_length=20)),
                ('action_msg', models.CharField(max_length=100)),
                ('read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('area_id', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('rainfall', models.FloatField()),
                ('altitude', models.IntegerField()),
                ('temprature', models.FloatField()),
                ('population', models.IntegerField()),
                ('water_source', models.IntegerField()),
                ('humidity', models.FloatField()),
                ('age_frequency_vector', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('slums_count', models.IntegerField()),
                ('victim_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('pt', 'Poultry'), ('gt', 'Goat'), ('pg', 'Pig'), ('bf', 'Buffalo'), ('sp', 'Ship')], max_length=2), size=None)),
                ('neighbours', models.ManyToManyField(related_name='_district_neighbours_+', to='disdata.District')),
            ],
        ),
    ]
