# Generated by Django 3.0.7 on 2020-07-21 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('disdata', '0015_auto_20200721_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='district_official',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
