# Generated by Django 3.0.7 on 2020-07-21 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disdata', '0016_district_district_official'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='neighbours',
        ),
    ]
