# Generated by Django 3.0.7 on 2020-07-21 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disdata', '0017_remove_district_neighbours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='action',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='notice',
            name='action_msg',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='notice',
            name='attn',
            field=models.CharField(choices=[('danger', 'danger'), ('warning', 'warning')], max_length=7),
        ),
    ]
