# Generated by Django 3.0.7 on 2020-07-22 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disdata', '0018_auto_20200721_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='category',
            field=models.CharField(choices=[('Water', 'Water borne'), ('Food', 'Food borne'), ('Vector', 'Vector borne'), ('Air', 'Air borne'), ('Animal', 'Animal transmitted')], max_length=6),
        ),
        migrations.AlterField(
            model_name='notice',
            name='action',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
