# Generated by Django 3.0.7 on 2020-07-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disdata', '0019_auto_20200722_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='msg_head',
            field=models.CharField(max_length=100),
        ),
    ]
