# Generated by Django 3.0.7 on 2020-07-23 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disdata', '0020_auto_20200722_0909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease',
            name='suseptible_prone_age',
        ),
        migrations.RemoveField(
            model_name='pincode',
            name='age_frequency_vector',
        ),
        migrations.RemoveField(
            model_name='pincode',
            name='altitude',
        ),
        migrations.RemoveField(
            model_name='pincode',
            name='humidity',
        ),
        migrations.RemoveField(
            model_name='pincode',
            name='population',
        ),
        migrations.RemoveField(
            model_name='pincode',
            name='rainfall',
        ),
        migrations.RemoveField(
            model_name='pincode',
            name='sanitation_condition',
        ),
        migrations.RemoveField(
            model_name='pincode',
            name='temprature',
        ),
        migrations.AddField(
            model_name='disease',
            name='incubation_period',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='district',
            name='wind',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='disease',
            name='category',
            field=models.CharField(choices=[('1', 'Water borne'), ('Food', 'Food borne'), ('2', 'Vector borne'), ('3', 'Air borne'), ('Animal', 'Animal transmitted')], max_length=6),
        ),
    ]
