# Generated by Django 3.0.7 on 2020-07-23 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disdata', '0021_auto_20200723_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='victim_id',
            field=models.CharField(choices=[('pt', 'Poultry'), ('gt', 'Goat'), ('pg', 'Pig'), ('bf', 'Buffalo'), ('sp', 'Sheep')], max_length=2),
        ),
    ]
