# Generated by Django 3.0.7 on 2020-07-23 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disdata', '0022_auto_20200723_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='info_symptoms',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
