# Generated by Django 3.0.7 on 2020-07-23 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disdata', '0023_disease_info_symptoms'),
    ]

    operations = [
        migrations.DeleteModel(
            name='District',
        ),
    ]
