# Generated by Django 3.0.7 on 2020-07-23 12:51

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('disdata', '0024_delete_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('rainfall', models.FloatField()),
                ('altitude', models.IntegerField()),
                ('temprature', models.FloatField()),
                ('population', models.IntegerField()),
                ('water_source', models.IntegerField()),
                ('humidity', models.FloatField()),
                ('age_frequency_vector', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('slums_count', models.IntegerField()),
                ('wind', models.FloatField()),
                ('victim_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('pt', 'Poultry'), ('gt', 'Goat'), ('pg', 'Pig'), ('bf', 'Buffalo'), ('sp', 'Ship')], max_length=2), size=None)),
                ('district_official', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pincode',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='disdata.District'),
        ),
    ]
