# Generated by Django 3.0.7 on 2020-07-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disdata', '0025_auto_20200723_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='density',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
