# Generated by Django 3.0.7 on 2020-07-25 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disdata', '0026_district_density'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disease',
            old_name='vacination_available',
            new_name='vaccination_available',
        ),
    ]
