# Generated by Django 3.0.7 on 2020-07-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disdata', '0027_auto_20200725_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='vaccination_regiment',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='disease',
            name='category',
            field=models.CharField(choices=[('1', 'Water borne'), ('2', 'Vector borne'), ('3', 'Air borne'), ('4', 'Animal transmitted')], max_length=6),
        ),
    ]
