# Generated by Django 3.0.7 on 2020-07-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disdata', '0028_auto_20200728_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='vaccination_regiment',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
