# Generated by Django 3.0.7 on 2020-08-02 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disdata', '0032_auto_20200802_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='action_msg',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
